config/routes.rb
Labsandcomps::Application.routes.draw do
  resources :labs

  resources :labworkers

end

app/models/lab.rb
class Lab < ActiveRecord::Base
	attr_accessible :room_number, :room_addr, :number_comp
	has_many :labworkers

	def get_workers()
		self.labworkers.to_json
	end
end

app/models/labworker.rb
class Labworker < ActiveRecord::Base
	attr_accessible :student_id, :student_name, :student_phone, :lab_id
	belongs_to :lab
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  # GET /labs
  # GET /labs.json
  def index
    @labs = Lab.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labs }
    end
  end

  # GET /labs/1
  # GET /labs/1.json
  def show
    @lab = Lab.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lab }
    end
  end

  # GET /labs/new
  # GET /labs/new.json
  def new
    @lab = Lab.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lab }
    end
  end

  # GET /labs/1/edit
  def edit
    @lab = Lab.find(params[:id])
  end

  # POST /labs
  # POST /labs.json
  def create
    @lab = Lab.new(params[:lab])

    respond_to do |format|
      if @lab.save
        format.html { redirect_to @lab, notice: 'Lab was successfully created.' }
        format.json { render json: @lab, status: :created, location: @lab }
      else
        format.html { render action: "new" }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labs/1
  # PUT /labs/1.json
  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(params[:lab])
        format.html { redirect_to @lab, notice: 'Lab was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labs/1
  # DELETE /labs/1.json
  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      format.html { redirect_to labs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/labworkers_controller.rb
class LabworkersController < ApplicationController
  # GET /labworkers
  # GET /labworkers.json
  def index
    @labworkers = Labworker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @labworkers }
    end
  end

  # GET /labworkers/1
  # GET /labworkers/1.json
  def show
    @labworker = Labworker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @labworker }
    end
  end

  # GET /labworkers/new
  # GET /labworkers/new.json
  def new
    @labworker = Labworker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @labworker }
    end
  end

  # GET /labworkers/1/edit
  def edit
    @labworker = Labworker.find(params[:id])
  end

  # POST /labworkers
  # POST /labworkers.json
  def create
    @labworker = Labworker.new(params[:labworker])

    respond_to do |format|
      if @labworker.save
        format.html { redirect_to @labworker, notice: 'Labworker was successfully created.' }
        format.json { render json: @labworker, status: :created, location: @labworker }
      else
        format.html { render action: "new" }
        format.json { render json: @labworker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /labworkers/1
  # PUT /labworkers/1.json
  def update
    @labworker = Labworker.find(params[:id])

    respond_to do |format|
      if @labworker.update_attributes(params[:labworker])
        format.html { redirect_to @labworker, notice: 'Labworker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @labworker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labworkers/1
  # DELETE /labworkers/1.json
  def destroy
    @labworker = Labworker.find(params[:id])
    @labworker.destroy

    respond_to do |format|
      format.html { redirect_to labworkers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labs_helper.rb
module LabsHelper
end

app/helpers/labworkers_helper.rb
module LabworkersHelper
end

app/views/labs/_form.html.erb
<%= form_for(@lab) do |f| %>
  <% if @lab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lab.errors.count, "error") %> prohibited this lab from being saved:</h2>

      <ul>
      <% @lab.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_number %><br />
    <%= f.number_field :room_number %>
  </div>
  <div class="field">
    <%= f.label :room_addr %><br />
    <%= f.text_field :room_addr %>
  </div>
  <div class="field">
    <%= f.label :number_comp %><br />
    <%= f.number_field :number_comp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labs/edit.html.erb
<h1>Editing lab</h1>

<%= render 'form' %>

<%= link_to 'Show', @lab %> |
<%= link_to 'Back', labs_path %>

app/views/labs/index.html.erb
<script type="text/javascript">
var h = new Object(); 

  function show_workers(id, hash){
    var element =  document.getElementById("" + id);
    if(h[id]){
      element.innerHTML = "";
      h[id] = false;
    } else {
      var text = "<table> <tr>" +
      "<th>Student id</th>" +
      "<th>Student name</th>" +
      "<th>Student phone</th>" +
      "</tr>";

      hash.forEach(function(entry) {
        text += "<tr><td>" + entry.student_id +
                "</td><td>" + entry.student_name +
                "</td><td>" + entry.student_phone + "</td></tr>";
      });
      element.innerHTML = text;
      h[id] = true;
    }
  }
</script>

<h1>Listing labs</h1>

<table>
  <tr>
    <th>Room number</th>
    <th>Room addr</th>
    <th>Number comp</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labs.each do |lab| %>
  <tr  >
    <td onclick="show_workers(<%= lab.id %>, <%= lab.get_workers() %>);"><%= lab.room_number %></td>
    <td><%= lab.room_addr %></td>
    <td><%= lab.number_comp %></td>
    <td><%= link_to 'Show', lab %></td>
    <td><%= link_to 'Edit', edit_lab_path(lab) %></td>
    <td><%= link_to 'Destroy', lab, confirm: 'Are you sure?', method: :delete %></td>
    <td id="<%= lab.id %>"></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lab', new_lab_path %>

app/views/labs/new.html.erb
<h1>New lab</h1>

<%= render 'form' %>

<%= link_to 'Back', labs_path %>

app/views/labs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Room number:</b>
  <%= @lab.room_number %>
</p>

<p>
  <b>Room addr:</b>
  <%= @lab.room_addr %>
</p>

<p>
  <b>Number comp:</b>
  <%= @lab.number_comp %>
</p>


<%= link_to 'Edit', edit_lab_path(@lab) %> |
<%= link_to 'Back', labs_path %>

app/views/labworkers/_form.html.erb
<%= form_for(@labworker) do |f| %>
  <% if @labworker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@labworker.errors.count, "error") %> prohibited this labworker from being saved:</h2>

      <ul>
      <% @labworker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br />
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :student_phone %><br />
    <%= f.number_field :student_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labworkers/edit.html.erb
<h1>Editing labworker</h1>

<%= render 'form' %>

<%= link_to 'Show', @labworker %> |
<%= link_to 'Back', labworkers_path %>

app/views/labworkers/index.html.erb
<h1>Listing labworkers</h1>

<table>
  <tr>
    <th>Student id</th>
    <th>Student name</th>
    <th>Student phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @labworkers.each do |labworker| %>
  <tr>
    <td><%= labworker.student_id %></td>
    <td><%= labworker.student_name %></td>
    <td><%= labworker.student_phone %></td>
    <td><%= link_to 'Show', labworker %></td>
    <td><%= link_to 'Edit', edit_labworker_path(labworker) %></td>
    <td><%= link_to 'Destroy', labworker, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Labworker', new_labworker_path %>

app/views/labworkers/new.html.erb
<h1>New labworker</h1>

<%= render 'form' %>

<%= link_to 'Back', labworkers_path %>

app/views/labworkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student id:</b>
  <%= @labworker.student_id %>
</p>

<p>
  <b>Student name:</b>
  <%= @labworker.student_name %>
</p>

<p>
  <b>Student phone:</b>
  <%= @labworker.student_phone %>
</p>


<%= link_to 'Edit', edit_labworker_path(@labworker) %> |
<%= link_to 'Back', labworkers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labsandcomps</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>